server:
  port: 8081

spring:
  security:
    oauth2:
#      resourceserver:
#        jwt:
#          jwk-set-uri: http://localhost:8080/.well-known/jwks.json
security:
  oauth2:
    resource:
      token-type:
    authorization:
      check-token-access: http://localhost:9005/oauth/check_token
