server:
  port: 8761

spring:
  application:
    name: orchid-eureka

eureka:
  hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false

