server:
  port: 8771
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


spring:
  application:
    name: orchid-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
#      routes:
#        - id: docker-example
#          uri: lb://docker-example
#          predicates:
#          - Path=/docker-example/**
#          filters:
#          - StripPrefix=1
#          - TokenRelay=


